version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2c7a5l2
  build:
    commands:
      - mvn install
      - docker build -t paws-pet-daniel .
      - docker tag paws-pet-daniel:latest public.ecr.aws/i2c7a5l2/paws-pet-daniel:latest
  post_build:
    commands:
      - docker push public.ecr.aws/i2c7a5l2/paws-pet-daniel:latest
artifacts:
  files:
    - target/*jar