version: 0.2

phases:
  install:
    commands:
      - docker login --username $DOCKER_USER --password $DOCKER_TOKEN

  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2c7a5l2
  build:
    commands:
      - mvn install
      - docker build -t pawspet .
      - docker save pawspet | gzip > pawspet.zip
      - docker tag pawspet:latest public.ecr.aws/i2c7a5l2/pawspet:latest
  post_build:
    commands:
      - docker push public.ecr.aws/i2c7a5l2/pawspet:latest
artifacts:
  files:
    - 'target/*jar'
    - 'scripts/**/*'
    - 'pawspet.tar.gz'
    - 'appspect.yaml'